### ISSUE TITLE
Cant build on Ubuntu 22.04

### ISSUE THREAD

**Issue by RodrigoSdeCarvalho** [mdrokz/rust-llama.cpp#15]
When trying to build it on my Ubuntu 22.04, I'm getting a build error.

```
cargo build
+ cargo build
   Compiling proc-macro2 v1.0.63
   Compiling quote v1.0.29
   Compiling libc v0.2.147
   Compiling memchr v2.5.0
   Compiling glob v0.3.1
   Compiling unicode-ident v1.0.9
   Compiling prettyplease v0.2.9
   Compiling cfg-if v1.0.0
   Compiling minimal-lexical v0.2.1
   Compiling bindgen v0.66.1
   Compiling regex-syntax v0.7.2
   Compiling either v1.8.1
   Compiling bitflags v2.3.3
   Compiling rustc-hash v1.1.0
   Compiling lazy_static v1.4.0
   Compiling shlex v1.1.0
   Compiling lazycell v1.3.0
   Compiling libloading v0.7.4
   Compiling log v0.4.19
   Compiling peeking_take_while v0.1.2
   Compiling cc v1.0.79
   Compiling clang-sys v1.6.1
   Compiling nom v7.1.3
   Compiling which v4.4.0
   Compiling syn v2.0.22
   Compiling regex v1.8.4
   Compiling cexpr v0.6.0
   Compiling llama_cpp_rs v0.3.0 (/home/rodrigo/Documents/SRS/rust-llama.cpp)
error: failed to run custom build command for `llama_cpp_rs v0.3.0 (/home/rodrigo/Documents/SRS/rust-llama.cpp)`

Caused by:
  process didn't exit successfully: `/home/rodrigo/Documents/SRS/rust-llama.cpp/target/debug/build/llama_cpp_rs-3e62109abc25cc59/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/rodrigo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.66.1/lib.rs:604:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by mdrokz** [comment]
> When trying to build it on my Ubuntu 22.04, I'm getting a build error.
> 
> ```
> cargo build
> + cargo build
>    Compiling proc-macro2 v1.0.63
>    Compiling quote v1.0.29
>    Compiling libc v0.2.147
>    Compiling memchr v2.5.0
>    Compiling glob v0.3.1
>    Compiling unicode-ident v1.0.9
>    Compiling prettyplease v0.2.9
>    Compiling cfg-if v1.0.0
>    Compiling minimal-lexical v0.2.1
>    Compiling bindgen v0.66.1
>    Compiling regex-syntax v0.7.2
>    Compiling either v1.8.1
>    Compiling bitflags v2.3.3
>    Compiling rustc-hash v1.1.0
>    Compiling lazy_static v1.4.0
>    Compiling shlex v1.1.0
>    Compiling lazycell v1.3.0
>    Compiling libloading v0.7.4
>    Compiling log v0.4.19
>    Compiling peeking_take_while v0.1.2
>    Compiling cc v1.0.79
>    Compiling clang-sys v1.6.1
>    Compiling nom v7.1.3
>    Compiling which v4.4.0
>    Compiling syn v2.0.22
>    Compiling regex v1.8.4
>    Compiling cexpr v0.6.0
>    Compiling llama_cpp_rs v0.3.0 (/home/rodrigo/Documents/SRS/rust-llama.cpp)
> error: failed to run custom build command for `llama_cpp_rs v0.3.0 (/home/rodrigo/Documents/SRS/rust-llama.cpp)`
> 
> Caused by:
>   process didn't exit successfully: `/home/rodrigo/Documents/SRS/rust-llama.cpp/target/debug/build/llama_cpp_rs-3e62109abc25cc59/build-script-build` (exit status: 101)
>   --- stdout
>   cargo:rerun-if-env-changed=TARGET
>   cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
> 
>   --- stderr
>   thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/rodrigo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.66.1/lib.rs:604:31
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

Do you have clang & llvm installed ?
