### ISSUE TITLE
Include ggml-metal.metal file in source code

### ISSUE THREAD

**Issue by pixelspark** [mdrokz/rust-llama.cpp#32]
To use Metal, the `ggml-metal.metal` file needs to be placed in the current directory. In the [llm crate](https://github.com/rustformers/llm) we have a little hack that patches `ggml-metal.m` to include the contents of that file directly in the source code, which is more convenient. See https://github.com/rustformers/llm/blob/9376078c12ea1990bd42e63432656819a056d379/crates/ggml/sys/build.rs#L198 

The same hack can be applied here too. I can make a PR if this is deemed a good idea...

**Comment by mdrokz** [comment]
> To use Metal, the `ggml-metal.metal` file needs to be placed in the current directory. In the [llm crate](https://github.com/rustformers/llm) we have a little hack that patches `ggml-metal.m` to include the contents of that file directly in the source code, which is more convenient. See https://github.com/rustformers/llm/blob/9376078c12ea1990bd42e63432656819a056d379/crates/ggml/sys/build.rs#L198
> 
> The same hack can be applied here too. I can make a PR if this is deemed a good idea...

This sounds god to me please go ahead and make an PR
