### ISSUE TITLE
Not cloning llama.cpp submodule

### ISSUE THREAD

**Issue by PainSled** [mdrokz/rust-llama.cpp#5]
This is in the readme, but it doesn't actually work:
```bash
git clone --recurse-submodules https://github.com/mdrokz/rust-llama.cpp
```

Running this within the repo, fixes it:
```bash
git submodule add https://github.com/ggerganov/llama.cpp/ llama.cpp
```
___
But it still won't build, though...
Looks like braking changes in llama.cpp

**Comment by mdrokz** [comment]
> This is in the readme, but it doesn't actually work:
> 
> ```shell
> git clone --recurse-submodules https://github.com/mdrokz/rust-llama.cpp
> ```
> 
> Running this within the repo, fixes it:
> 
> ```shell
> git submodule add https://github.com/ggerganov/llama.cpp/ llama.cpp
> ```
> 
> But it still won't build, though... Looks like braking changes in llama.cpp

Hey im currently fixing this the build relies on a specific commit from llama.cpp

**Comment by mdrokz** [comment]
I created a pr for this #6 this should fix the cloning and build issue
